### ISSUE TITLE
Consider replacing node-then-eos dependency

### ISSUE THREAD

**Issue by sammacbeth** [RangerMauve/mostly-minimal-spanning-tree#2]
In environments where the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) prevents `eval` (e.g. browser extensions), the `thenify` module used by `node-then-eos` cannot be used, causing an exception on import. This is because `thenify` is implemented using [`eval`](https://github.com/thenables/thenify/blob/master/index.js#L17).

![Screenshot 2019-09-27 at 09 37 22](https://user-images.githubusercontent.com/248111/65753507-74b09780-e10f-11e9-8adf-f9d7098854bf.png)

**Comment by RangerMauve** [comment]
Oh jeeze. Thank you for pointing this out!

**Comment by RangerMauve** [comment]
Could you try out the replace-eos branch to see if it works for you?

**Comment by sammacbeth** [comment]
Yep, that works. Thanks!

**Comment by RangerMauve** [comment]
Out in 1.0.1! :D
